# Generated by Django 4.0.2 on 2022-02-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('position', models.CharField(max_length=100, verbose_name='Имя')),
                ('recruitment', models.DateField(verbose_name='Дата приема на работу')),
                ('salary', models.FloatField(verbose_name='Зарплата')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='staff.employee', verbose_name='Начальник')),
            ],
        ),
    ]
